<a href="https://colab.research.google.com/github/belindacarolam04/pandas_learning/blob/main/Data_Selection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**DATA SELECTION**

In [69]:
import pandas as pd
import numpy as np

In [70]:
import kagglehub

path = kagglehub.dataset_download(
    "shivasingh4945/enhanced-breast-cancer-diagnostic-dataset"
)

print("Path to dataset files:", path)

Using Colab cache for faster access to the 'enhanced-breast-cancer-diagnostic-dataset' dataset.
Path to dataset files: /kaggle/input/enhanced-breast-cancer-diagnostic-dataset

In [71]:
import os

print(os.listdir(path))

['breast_cancer_enhanced_dataset.csv']

In [72]:
df=pd.read_csv(f"{path}/breast_cancer_enhanced_dataset.csv")

**df.columns**

---

to know about the columns in the dataset

In [73]:
print(df.columns)

Index(['id', 'diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'shape_irregularity', 'border_complexity',
       'tumor_aggressiveness', 'radius_texture_interaction',
       'radius_concavity_interaction', 'concavity_density',
       'malignancy_risk_score'],
      dtype='object')

**df.info**

---

it shows column,missing values and datatype

In [74]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5500 entries, 0 to 5499
Data columns (total 17 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   id                            5500 non-null   float64
 1   diagnosis                     5500 non-null   object
 2   radius_mean                   5500 non-null   float64
 3   texture_mean                  5500 non-null   float64
 4   perimeter_mean                5500 non-null   float64
 5   area_mean                     5500 non-null   float64
 6   smoothness_mean               5500 non-null   float64
 7   compactness_mean              5500 non-null   float64
 8   concavity_mean                5500 non-null   float64
 9   concave points_mean           5500 non-null   float64
 10  shape_irregularity            5500 non-null   float64
 11  border_complexity             5500 non-null   float64
 12  tumor_aggressiveness          5500 non-null   float64
 13  radius_texture_interaction    5500 non-null   float64
 14  radius_concavity_interaction  5500 non-null   float64
 15  concavity_density             5500 non-null   float64
 16  malignancy_risk_score         5500 non-null   float64
dtypes: float64(16), object(1)
memory usage: 730.6+ KB

**df.loc**

---
uses label names for selection

In [75]:
df['sequential_index'] = range(1, len(df) + 1)

In [76]:
print(df.head())

             id diagnosis  radius_mean  texture_mean  perimeter_mean  \
0  5.683796e+06         B    11.829858     21.726166       75.154378
1 -6.253379e+06         B    10.991150     17.103260       71.798929
2  4.213892e+06         M    21.433519     15.092437      142.753006
3 -2.986069e+06         B    11.700452     14.872127       74.154481
4  6.469594e+05         B    13.259377     17.212990       83.621014

     area_mean  smoothness_mean  compactness_mean  concavity_mean  \
0   435.022394         0.087089          0.050717        0.015868
1   381.386295         0.089339          0.109498        0.097344
2  1392.399890         0.099557          0.152079        0.193372
3   404.112556         0.101291          0.077563        0.043749
4   521.124238         0.072905          0.043312        0.046983

   concave points_mean  shape_irregularity  border_complexity  \
0             0.011641            0.078226           0.000185
1             0.035629            0.242470           0.003468
2             0.126922            0.472373           0.024543
3             0.028747            0.150059           0.001258
4             0.010096            0.100391           0.000474

   tumor_aggressiveness  radius_texture_interaction  \
0              0.026075                  257.017451
1              0.080823                  187.984489
2              0.157458                  323.484034
3              0.050020                  174.010599
4              0.033464                  228.233523

   radius_concavity_interaction  concavity_density  malignancy_risk_score  \
0                      0.187718           0.000036              22.433798
1                      1.069921           0.000255              24.021839
2                      4.144647           0.000139              49.053992
3                      0.511885           0.000108              23.276145
4                      0.622960           0.000090              25.647074

   sequential_index
0                 1
1                 2
2                 3
3                 4
4                 5

**ROW SELECTION**

In [77]:
df.dtypes

id                              float64
diagnosis                        object
radius_mean                     float64
texture_mean                    float64
perimeter_mean                  float64
area_mean                       float64
smoothness_mean                 float64
compactness_mean                float64
concavity_mean                  float64
concave points_mean             float64
shape_irregularity              float64
border_complexity               float64
tumor_aggressiveness            float64
radius_texture_interaction      float64
radius_concavity_interaction    float64
concavity_density               float64
malignancy_risk_score           float64
sequential_index                  int64
dtype: object

1.SELECT SINGLE ROW

In [78]:
df.loc[888]

id                              2118847.377186
diagnosis                                    M
radius_mean                          12.886441
texture_mean                         21.861671
perimeter_mean                       87.640772
area_mean                           505.142811
smoothness_mean                       0.127922
compactness_mean                      0.192887
concavity_mean                        0.187847
concave points_mean                     0.0939
shape_irregularity                    0.474633
border_complexity                     0.017639
tumor_aggressiveness                  0.158211
radius_texture_interaction          281.719124
radius_concavity_interaction          2.420683
concavity_density                     0.000372
malignancy_risk_score                32.175474
sequential_index                           889
Name: 888, dtype: object

2.SELECT MULTIPLE ROWS

In [79]:
df.loc[[889,900]]

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,shape_irregularity,border_complexity,tumor_aggressiveness,radius_texture_interaction,radius_concavity_interaction,concavity_density,malignancy_risk_score,sequential_index
889,9.408815e+06,B,13.094861,15.263309,84.950901,543.999344,0.093802,0.085101,0.090382,0.035118,0.210601,0.003174,0.070200,199.870920,1.183540,0.000166,27.648946,890
900,8.130169e+07,M,19.509811,21.225940,129.885677,1200.718786,0.108973,0.162424,0.195893,0.128506,0.486824,0.025173,0.162275,414.114079,3.821837,0.000163,45.458852,901

3.ROW RANGE

In [80]:
df.loc[800:810]

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,shape_irregularity,border_complexity,tumor_aggressiveness,radius_texture_interaction,radius_concavity_interaction,concavity_density,malignancy_risk_score,sequential_index
800,1.180073e+06,M,18.144620,19.909666,120.192905,1048.471697,0.094881,0.107409,0.110668,0.072643,0.290720,0.008039,0.096907,361.253327,2.008035,0.000106,39.167158,801
801,-8.027075e+05,M,13.314017,19.831786,86.419693,569.431756,0.090856,0.061978,0.059127,0.033693,0.154798,0.001992,0.051599,264.040735,0.787217,0.000104,27.253917,802
802,-3.655427e+06,B,11.927886,17.271323,76.661388,428.449761,0.083020,0.056302,0.025142,0.024437,0.105881,0.000614,0.035294,206.010373,0.299891,0.000059,23.386802,803
803,-3.491219e+06,B,10.972783,20.044131,71.264128,381.772716,0.085388,0.044203,0.007066,0.004934,0.056204,0.000035,0.018735,219.939895,0.077536,0.000019,20.859238,804
804,-1.511895e+05,B,11.522599,19.081146,74.586469,401.252951,0.085722,0.076048,0.054449,0.016159,0.146655,0.000880,0.048885,219.864398,0.627391,0.000136,23.292449,805
805,1.001572e+07,M,18.180737,16.582458,116.963078,996.520008,0.090059,0.121630,0.111117,0.062185,0.294932,0.006910,0.098311,301.481318,2.020194,0.000112,38.118502,806
806,6.297720e+06,B,11.700763,19.315402,73.626694,435.173834,0.088541,0.051492,0.015236,0.011382,0.078109,0.000173,0.026036,226.004931,0.178269,0.000035,21.997294,807
807,7.022206e+05,M,14.344760,22.275446,97.706506,641.933028,0.105470,0.198092,0.214803,0.087510,0.500405,0.018798,0.166802,319.535920,3.081299,0.000335,35.570657,808
808,1.257650e+07,B,10.006427,17.474747,64.527990,305.473857,0.106306,0.084563,0.015391,0.019783,0.119738,0.000304,0.039913,174.859778,0.154008,0.000050,19.512961,809
809,4.975341e+06,M,20.430635,29.205521,140.567497,1249.338026,0.117992,0.276907,0.356034,0.152179,0.785120,0.054181,0.261707,596.687350,7.273991,0.000285,52.954856,810
810,-1.543743e+04,M,17.291947,16.197542,116.387114,915.283314,0.118458,0.228299,0.218835,0.139561,0.586695,0.030541,0.195565,280.087038,3.784085,0.000239,42.379659,811

4.SELECT ONE VALUE

In [81]:
print(df.loc[1000,'radius_mean'].round(2))

9.73

5.ENTIRE ROW

In [82]:
df.loc[1,:]

id                             -6253379.305707
diagnosis                                    B
radius_mean                           10.99115
texture_mean                          17.10326
perimeter_mean                       71.798929
area_mean                           381.386295
smoothness_mean                       0.089339
compactness_mean                      0.109498
concavity_mean                        0.097344
concave points_mean                   0.035629
shape_irregularity                     0.24247
border_complexity                     0.003468
tumor_aggressiveness                  0.080823
radius_texture_interaction          187.984489
radius_concavity_interaction          1.069921
concavity_density                     0.000255
malignancy_risk_score                24.021839
sequential_index                             2
Name: 1, dtype: object

6.UPDATE VALUES

In [83]:
df.loc[1,'diagnosis']='M'
print(df.loc[1])

id                             -6253379.305707
diagnosis                                    M
radius_mean                           10.99115
texture_mean                          17.10326
perimeter_mean                       71.798929
area_mean                           381.386295
smoothness_mean                       0.089339
compactness_mean                      0.109498
concavity_mean                        0.097344
concave points_mean                   0.035629
shape_irregularity                     0.24247
border_complexity                     0.003468
tumor_aggressiveness                  0.080823
radius_texture_interaction          187.984489
radius_concavity_interaction          1.069921
concavity_density                     0.000255
malignancy_risk_score                24.021839
sequential_index                             2
Name: 1, dtype: object

**COLUMN SELECTION**

1.ONE COLUMN

In [84]:
df.loc[:,'area_mean']

0        435.022394
1        381.386295
2       1392.399890
3        404.112556
4        521.124238
           ...
5495     429.895271
5496     580.072530
5497    1129.627896
5498    1340.103257
5499    1269.726727
Name: area_mean, Length: 5500, dtype: float64

2.MULTIPLE SELECTION

In [85]:
df.loc[:,['id','diagnosis','malignancy_risk_score']]

                id diagnosis  malignancy_risk_score
0     5.683796e+06         B              22.433798
1    -6.253379e+06         M              24.021839
2     4.213892e+06         M              49.053992
3    -2.986069e+06         B              23.276145
4     6.469594e+05         B              25.647074
...            ...       ...                    ...
5495  2.909607e+06         B              24.344788
5496  4.399236e+05         B              26.379882
5497 -4.461865e+06         M              43.224263
5498  7.519916e+06         M              52.471548
5499 -3.163711e+06         M              43.364274

[5500 rows x 3 columns]

**SPECIFIC ROW AND COLUMN SELECTION**

In [86]:
df.loc[[4,9,6],['id','diagnosis','malignancy_risk_score']]

             id diagnosis  malignancy_risk_score
4  6.469594e+05         B              25.647074
9  1.403596e+06         M              41.764167
6  6.104780e+06         B              25.061439

**CONDITIONAL SELECTION**

In [87]:
df.loc[df['diagnosis']=='B']

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,shape_irregularity,border_complexity,tumor_aggressiveness,radius_texture_interaction,radius_concavity_interaction,concavity_density,malignancy_risk_score,sequential_index
0,5.683796e+06,B,11.829858,21.726166,75.154378,435.022394,0.087089,0.050717,0.015868,0.011641,0.078226,0.000185,0.026075,257.017451,0.187718,0.000036,22.433798,1
3,-2.986069e+06,B,11.700452,14.872127,74.154481,404.112556,0.101291,0.077563,0.043749,0.028747,0.150059,0.001258,0.050020,174.010599,0.511885,0.000108,23.276145,4
4,6.469594e+05,B,13.259377,17.212990,83.621014,521.124238,0.072905,0.043312,0.046983,0.010096,0.100391,0.000474,0.033464,228.233523,0.622960,0.000090,25.647074,5
5,-4.581518e+05,B,11.620937,16.155888,76.026791,436.142831,0.112669,0.095446,0.036704,0.031314,0.163464,0.001149,0.054488,187.746558,0.426530,0.000084,23.612382,6
6,6.104780e+06,B,12.166927,14.868031,78.601322,428.659208,0.103159,0.090379,0.066778,0.027997,0.185154,0.001870,0.061718,180.898245,0.812485,0.000156,25.061439,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5490,8.177530e+06,B,10.720594,20.395350,69.557507,346.798775,0.108093,0.131209,0.084799,0.026587,0.242595,0.002255,0.080865,218.650272,0.909092,0.000245,22.854174,5491
5491,1.599844e+07,B,11.972502,24.934269,76.618332,430.183742,0.102860,0.094415,0.055275,0.042504,0.192194,0.002349,0.064065,298.525577,0.661777,0.000128,24.592183,5492
5494,2.477849e+06,B,10.791094,17.207447,71.872111,370.878589,0.088964,0.110048,0.097307,0.037295,0.244650,0.003629,0.081550,185.687173,1.050053,0.000262,24.030855,5495
5495,2.909607e+06,B,11.688492,18.217548,75.277156,429.895271,0.113777,0.104274,0.069515,0.034620,0.208409,0.002407,0.069470,212.935657,0.812528,0.000162,24.344788,5496
5496,4.399236e+05,B,13.831066,19.454900,88.204429,580.072530,0.087240,0.061584,0.012322,0.022518,0.096424,0.000277,0.032141,269.082007,0.170427,0.000021,26.379882,5497

**MULTIPLE CONDITION**

In [99]:
df.loc[(df['diagnosis']=='M') & (df['radius_mean']>15)]

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,shape_irregularity,border_complexity,tumor_aggressiveness,radius_texture_interaction,radius_concavity_interaction,concavity_density,malignancy_risk_score,sequential_index
2,4.213892e+06,M,21.433519,15.092437,142.753006,1392.399890,0.099557,0.152079,0.193372,0.126922,0.472373,0.024543,0.157458,323.484034,4.144647,0.000139,49.053992,3
9,1.403596e+06,M,18.083293,18.692756,120.690753,1034.577981,0.115221,0.150960,0.177470,0.105356,0.433786,0.018698,0.144595,338.026597,3.209245,0.000172,41.764167,10
13,-3.262408e+06,M,18.640021,21.792118,123.235652,1134.816423,0.101391,0.141004,0.159887,0.087485,0.388375,0.013988,0.129458,406.205533,2.980289,0.000141,41.653199,14
14,9.365728e+07,M,18.042574,20.831732,116.695172,982.798351,0.103916,0.129658,0.120366,0.087428,0.337453,0.010523,0.112484,375.858062,2.171721,0.000122,38.879310,15
17,1.988092e+05,M,17.162790,24.791563,115.080640,947.778697,0.107023,0.181751,0.169390,0.079198,0.430339,0.013415,0.143446,425.492385,2.907203,0.000179,39.275546,18
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5488,-1.645301e+06,M,16.635795,20.132222,106.180548,855.747914,0.074844,0.067425,0.037122,0.022992,0.127539,0.000854,0.042513,334.915522,0.617554,0.000043,32.206941,5489
5489,2.806541e+05,M,15.044728,16.551363,99.057215,733.731131,0.089081,0.094820,0.076501,0.039171,0.210492,0.002997,0.070164,249.010765,1.150940,0.000104,31.417283,5490
5497,-4.461865e+06,M,19.403923,18.152520,127.631265,1129.627896,0.104142,0.144262,0.164108,0.094511,0.402881,0.015510,0.134294,352.230108,3.184337,0.000145,43.224263,5498
5498,7.519916e+06,M,20.946319,25.233666,142.498720,1340.103257,0.109454,0.226277,0.316075,0.148336,0.690688,0.046885,0.230229,528.552405,6.620608,0.000236,52.471548,5499
5499,-3.163711e+06,M,19.936731,22.043719,129.216656,1269.726727,0.098140,0.102896,0.146180,0.096857,0.345933,0.014159,0.115311,439.479696,2.914349,0.000115,43.364274,5500

**df.iloc**

---
use positions instead of labels

1.SINGLE ROW

In [88]:
df.iloc[1]

id                             -6253379.305707
diagnosis                                    M
radius_mean                           10.99115
texture_mean                          17.10326
perimeter_mean                       71.798929
area_mean                           381.386295
smoothness_mean                       0.089339
compactness_mean                      0.109498
concavity_mean                        0.097344
concave points_mean                   0.035629
shape_irregularity                     0.24247
border_complexity                     0.003468
tumor_aggressiveness                  0.080823
radius_texture_interaction          187.984489
radius_concavity_interaction          1.069921
concavity_density                     0.000255
malignancy_risk_score                24.021839
sequential_index                             2
Name: 1, dtype: object

2.SINGLE VALUE

In [89]:
df.iloc[1000,1]

'B'

3.ROW RANGE

---

end position is excluded

In [90]:
df.iloc[2:9]

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,shape_irregularity,border_complexity,tumor_aggressiveness,radius_texture_interaction,radius_concavity_interaction,concavity_density,malignancy_risk_score,sequential_index
2,4.213892e+06,M,21.433519,15.092437,142.753006,1392.399890,0.099557,0.152079,0.193372,0.126922,0.472373,0.024543,0.157458,323.484034,4.144647,0.000139,49.053992,3
3,-2.986069e+06,B,11.700452,14.872127,74.154481,404.112556,0.101291,0.077563,0.043749,0.028747,0.150059,0.001258,0.050020,174.010599,0.511885,0.000108,23.276145,4
4,6.469594e+05,B,13.259377,17.212990,83.621014,521.124238,0.072905,0.043312,0.046983,0.010096,0.100391,0.000474,0.033464,228.233523,0.622960,0.000090,25.647074,5
5,-4.581518e+05,B,11.620937,16.155888,76.026791,436.142831,0.112669,0.095446,0.036704,0.031314,0.163464,0.001149,0.054488,187.746558,0.426530,0.000084,23.612382,6
6,6.104780e+06,B,12.166927,14.868031,78.601322,428.659208,0.103159,0.090379,0.066778,0.027997,0.185154,0.001870,0.061718,180.898245,0.812485,0.000156,25.061439,7
7,9.398100e+07,B,13.443279,18.669093,87.810591,564.287299,0.106001,0.115531,0.083967,0.054183,0.253681,0.004550,0.084560,250.973833,1.128795,0.000149,28.767221,8
8,2.722075e+06,B,8.743292,15.826895,54.991483,253.178665,0.114348,0.080234,0.040824,0.019867,0.140925,0.000811,0.046975,138.379160,0.356940,0.000161,17.450987,9

4.MULTIPLE ROWS

In [91]:
df.iloc[[7,24]]

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,shape_irregularity,border_complexity,tumor_aggressiveness,radius_texture_interaction,radius_concavity_interaction,concavity_density,malignancy_risk_score,sequential_index
7,9.398100e+07,B,13.443279,18.669093,87.810591,564.287299,0.106001,0.115531,0.083967,0.054183,0.253681,0.00455,0.084560,250.973833,1.128795,0.000149,28.767221,8
24,8.829697e+06,M,18.092566,16.889014,117.057384,993.254133,0.089382,0.125641,0.111972,0.061983,0.299596,0.00694,0.099865,305.565608,2.025858,0.000113,38.136370,25

5.SPECIFIC ROWS AND COLUMNS

In [92]:
df.iloc[[1,2],[2,4]]

   radius_mean  perimeter_mean
1    10.991150       71.798929
2    21.433519      142.753006

6.ENTIRE COLUMN

In [93]:
df.iloc[:,3]

0       21.726166
1       17.103260
2       15.092437
3       14.872127
4       17.212990
          ...
5495    18.217548
5496    19.454900
5497    18.152520
5498    25.233666
5499    22.043719
Name: texture_mean, Length: 5500, dtype: float64

6.ENTIRE ROW

In [94]:
df.iloc[3,:]

id                             -2986069.269824
diagnosis                                    B
radius_mean                          11.700452
texture_mean                         14.872127
perimeter_mean                       74.154481
area_mean                           404.112556
smoothness_mean                       0.101291
compactness_mean                      0.077563
concavity_mean                        0.043749
concave points_mean                   0.028747
shape_irregularity                    0.150059
border_complexity                     0.001258
tumor_aggressiveness                   0.05002
radius_texture_interaction          174.010599
radius_concavity_interaction          0.511885
concavity_density                     0.000108
malignancy_risk_score                23.276145
sequential_index                             4
Name: 3, dtype: object

7.MULTIPLE ROWS AND COLUMNS

In [96]:
df.iloc[2:5,0:4]

             id diagnosis  radius_mean  texture_mean
2  4.213892e+06         M    21.433519     15.092437
3 -2.986069e+06         B    11.700452     14.872127
4  6.469594e+05         B    13.259377     17.212990

8.EVERY N ROWS

In [98]:
df.iloc[: : 4]

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,shape_irregularity,border_complexity,tumor_aggressiveness,radius_texture_interaction,radius_concavity_interaction,concavity_density,malignancy_risk_score,sequential_index
0,5.683796e+06,B,11.829858,21.726166,75.154378,435.022394,0.087089,0.050717,0.015868,0.011641,0.078226,0.000185,0.026075,257.017451,0.187718,0.000036,22.433798,1
4,6.469594e+05,B,13.259377,17.212990,83.621014,521.124238,0.072905,0.043312,0.046983,0.010096,0.100391,0.000474,0.033464,228.233523,0.622960,0.000090,25.647074,5
8,2.722075e+06,B,8.743292,15.826895,54.991483,253.178665,0.114348,0.080234,0.040824,0.019867,0.140925,0.000811,0.046975,138.379160,0.356940,0.000161,17.450987,9
12,4.121092e+06,B,12.738915,11.986116,81.065538,497.092137,0.087289,0.057679,0.024522,0.023111,0.105312,0.000567,0.035104,152.690115,0.312379,0.000049,24.641929,13
16,1.682542e+06,B,13.085290,15.955541,84.075209,510.242432,0.100669,0.076768,0.061316,0.032557,0.170641,0.001996,0.056880,208.782888,0.802335,0.000120,26.636951,17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5480,-4.182449e+06,M,21.091955,25.246650,143.420631,1353.941807,0.109253,0.223829,0.318068,0.147856,0.689753,0.047028,0.229918,532.501214,6.708674,0.000235,52.776256,5481
5484,-3.312200e+05,B,10.386814,18.478996,67.189602,332.768786,0.107367,0.066532,0.022894,0.017170,0.106597,0.000393,0.035532,191.937908,0.237794,0.000069,20.395709,5485
5488,-1.645301e+06,M,16.635795,20.132222,106.180548,855.747914,0.074844,0.067425,0.037122,0.022992,0.127539,0.000854,0.042513,334.915522,0.617554,0.000043,32.206941,5489
5492,1.733785e+06,M,13.736838,24.919536,88.238364,579.112750,0.095047,0.086599,0.085256,0.045838,0.217692,0.003908,0.072564,342.315635,1.171146,0.000147,28.771136,5493
5496,4.399236e+05,B,13.831066,19.454900,88.204429,580.072530,0.087240,0.061584,0.012322,0.022518,0.096424,0.000277,0.032141,269.082007,0.170427,0.000021,26.379882,5497