<a href="https://colab.research.google.com/github/belindacarolam04/pandas_learning/blob/main/Filtering.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
import kagglehub

path = kagglehub.dataset_download(
    "shivasingh4945/enhanced-breast-cancer-diagnostic-dataset"
)

print("Path to dataset files:", path)

Downloading to /root/.cache/kagglehub/datasets/shivasingh4945/enhanced-breast-cancer-diagnostic-dataset/1.archive...

100%|██████████| 812k/812k [00:00<00:00, 55.1MB/s]

Extracting files...
Path to dataset files: /root/.cache/kagglehub/datasets/shivasingh4945/enhanced-breast-cancer-diagnostic-dataset/versions/1

In [3]:
import os

print(os.listdir(path))

['breast_cancer_enhanced_dataset.csv']

In [4]:
df=pd.read_csv(f"{path}/breast_cancer_enhanced_dataset.csv")

1.SINGLE COLUMN FILTER

In [10]:
df[df['radius_mean']>=28]

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,shape_irregularity,border_complexity,tumor_aggressiveness,radius_texture_interaction,radius_concavity_interaction,concavity_density,malignancy_risk_score
373,9.557969e+06,M,28.226659,18.475831,188.331034,2496.606181,0.114306,0.151275,0.322009,0.158492,0.631776,0.051036,0.210592,521.510983,9.089236,0.000129,66.151952
497,3.680075e+06,M,28.134575,18.675329,188.730042,2507.933865,0.113976,0.151470,0.319505,0.160258,0.631233,0.051203,0.210411,525.422450,8.989126,0.000127,66.210220
575,1.485636e+07,M,28.037554,18.505108,187.798686,2507.982355,0.115066,0.151185,0.319866,0.157963,0.629014,0.050527,0.209671,518.837982,8.968264,0.000128,65.904800
1267,1.298915e+06,M,28.180977,18.450093,188.271693,2499.413980,0.114077,0.153222,0.323629,0.159020,0.635870,0.051463,0.211957,519.941649,9.120178,0.000129,66.179382
2653,9.562581e+06,M,28.085196,18.434952,188.552674,2507.574607,0.114925,0.153464,0.321570,0.160146,0.635180,0.051498,0.211727,517.749251,9.031344,0.000128,66.202363
3024,1.024661e+07,M,28.341004,18.354148,187.179338,2495.754833,0.114256,0.149376,0.317255,0.158960,0.625592,0.050431,0.208531,520.174975,8.991326,0.000127,65.785470
4039,8.009618e+06,M,28.067674,18.477850,188.983008,2501.568981,0.114228,0.153200,0.324914,0.160105,0.638219,0.052020,0.212740,518.630280,9.119588,0.000130,66.388146
4170,1.721022e+07,M,28.162806,18.423548,187.660155,2495.909622,0.113917,0.153775,0.321273,0.160117,0.635165,0.051441,0.211722,518.858798,9.047941,0.000129,65.990493
4957,1.340805e+07,M,28.223878,18.528421,188.826181,2494.185419,0.114415,0.150205,0.321311,0.157775,0.629291,0.050695,0.209764,522.943912,9.068653,0.000129,66.239684

2.MULTIPLE COLUMN FILTER

In [14]:
df[(df['radius_mean'] >= 28) & (df['malignancy_risk_score'] >= 66)]

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,shape_irregularity,border_complexity,tumor_aggressiveness,radius_texture_interaction,radius_concavity_interaction,concavity_density,malignancy_risk_score
373,9.557969e+06,M,28.226659,18.475831,188.331034,2496.606181,0.114306,0.151275,0.322009,0.158492,0.631776,0.051036,0.210592,521.510983,9.089236,0.000129,66.151952
497,3.680075e+06,M,28.134575,18.675329,188.730042,2507.933865,0.113976,0.151470,0.319505,0.160258,0.631233,0.051203,0.210411,525.422450,8.989126,0.000127,66.210220
1267,1.298915e+06,M,28.180977,18.450093,188.271693,2499.413980,0.114077,0.153222,0.323629,0.159020,0.635870,0.051463,0.211957,519.941649,9.120178,0.000129,66.179382
2653,9.562581e+06,M,28.085196,18.434952,188.552674,2507.574607,0.114925,0.153464,0.321570,0.160146,0.635180,0.051498,0.211727,517.749251,9.031344,0.000128,66.202363
4039,8.009618e+06,M,28.067674,18.477850,188.983008,2501.568981,0.114228,0.153200,0.324914,0.160105,0.638219,0.052020,0.212740,518.630280,9.119588,0.000130,66.388146
4957,1.340805e+07,M,28.223878,18.528421,188.826181,2494.185419,0.114415,0.150205,0.321311,0.157775,0.629291,0.050695,0.209764,522.943912,9.068653,0.000129,66.239684

3.isin METHOD

In [41]:
df[(df['diagnosis']).isin(['M'])]

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,shape_irregularity,border_complexity,tumor_aggressiveness,radius_texture_interaction,radius_concavity_interaction,concavity_density,malignancy_risk_score
2,4.213892e+06,M,21.433519,15.092437,142.753006,1392.399890,0.099557,0.152079,0.193372,0.126922,0.472373,0.024543,0.157458,323.484034,4.144647,0.000139,49.053992
9,1.403596e+06,M,18.083293,18.692756,120.690753,1034.577981,0.115221,0.150960,0.177470,0.105356,0.433786,0.018698,0.144595,338.026597,3.209245,0.000172,41.764167
13,-3.262408e+06,M,18.640021,21.792118,123.235652,1134.816423,0.101391,0.141004,0.159887,0.087485,0.388375,0.013988,0.129458,406.205533,2.980289,0.000141,41.653199
14,9.365728e+07,M,18.042574,20.831732,116.695172,982.798351,0.103916,0.129658,0.120366,0.087428,0.337453,0.010523,0.112484,375.858062,2.171721,0.000122,38.879310
17,1.988092e+05,M,17.162790,24.791563,115.080640,947.778697,0.107023,0.181751,0.169390,0.079198,0.430339,0.013415,0.143446,425.492385,2.907203,0.000179,39.275546
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5492,1.733785e+06,M,13.736838,24.919536,88.238364,579.112750,0.095047,0.086599,0.085256,0.045838,0.217692,0.003908,0.072564,342.315635,1.171146,0.000147,28.771136
5493,-5.187229e+06,M,14.948190,16.846998,98.779466,658.925449,0.116212,0.164118,0.170060,0.090065,0.424243,0.015317,0.141414,251.832128,2.542095,0.000258,34.935053
5497,-4.461865e+06,M,19.403923,18.152520,127.631265,1129.627896,0.104142,0.144262,0.164108,0.094511,0.402881,0.015510,0.134294,352.230108,3.184337,0.000145,43.224263
5498,7.519916e+06,M,20.946319,25.233666,142.498720,1340.103257,0.109454,0.226277,0.316075,0.148336,0.690688,0.046885,0.230229,528.552405,6.620608,0.000236,52.471548
5499,-3.163711e+06,M,19.936731,22.043719,129.216656,1269.726727,0.098140,0.102896,0.146180,0.096857,0.345933,0.014159,0.115311,439.479696,2.914349,0.000115,43.364274

In [31]:
df[df['malignancy_risk_score'].isin([60, 67])]  #It checks whether there is any value that has 60 or 67

Empty DataFrame
Columns: [id, diagnosis, radius_mean, texture_mean, perimeter_mean, area_mean, smoothness_mean, compactness_mean, concavity_mean, concave points_mean, shape_irregularity, border_complexity, tumor_aggressiveness, radius_texture_interaction, radius_concavity_interaction, concavity_density, malignancy_risk_score]
Index: []

4.between METHOD

In [37]:
df[df['malignancy_risk_score'].between(65, 67)] #It checks whether there are values in between the mentioned values

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,shape_irregularity,border_complexity,tumor_aggressiveness,radius_texture_interaction,radius_concavity_interaction,concavity_density,malignancy_risk_score
373,9.557969e+06,M,28.226659,18.475831,188.331034,2496.606181,0.114306,0.151275,0.322009,0.158492,0.631776,0.051036,0.210592,521.510983,9.089236,0.000129,66.151952
497,3.680075e+06,M,28.134575,18.675329,188.730042,2507.933865,0.113976,0.151470,0.319505,0.160258,0.631233,0.051203,0.210411,525.422450,8.989126,0.000127,66.210220
575,1.485636e+07,M,28.037554,18.505108,187.798686,2507.982355,0.115066,0.151185,0.319866,0.157963,0.629014,0.050527,0.209671,518.837982,8.968264,0.000128,65.904800
1267,1.298915e+06,M,28.180977,18.450093,188.271693,2499.413980,0.114077,0.153222,0.323629,0.159020,0.635870,0.051463,0.211957,519.941649,9.120178,0.000129,66.179382
1936,1.570997e+07,M,27.936746,18.297444,188.678884,2488.971319,0.114177,0.151583,0.314148,0.160735,0.626467,0.050495,0.208822,511.171052,8.776271,0.000126,66.025990
2653,9.562581e+06,M,28.085196,18.434952,188.552674,2507.574607,0.114925,0.153464,0.321570,0.160146,0.635180,0.051498,0.211727,517.749251,9.031344,0.000128,66.202363
2683,9.124480e+08,M,27.281185,26.371081,187.065254,2498.834947,0.108807,0.199534,0.361254,0.169898,0.730685,0.061376,0.243562,719.434333,9.855425,0.000145,66.865392
3024,1.024661e+07,M,28.341004,18.354148,187.179338,2495.754833,0.114256,0.149376,0.317255,0.158960,0.625592,0.050431,0.208531,520.174975,8.991326,0.000127,65.785470
3507,9.107752e+08,M,27.335729,26.508509,187.694219,2494.220653,0.107821,0.198630,0.361802,0.167702,0.728134,0.060675,0.242711,724.629422,9.890131,0.000145,66.995094
3867,9.115380e+08,M,27.426697,26.285319,186.236848,2507.547634,0.108528,0.200872,0.362085,0.167675,0.730632,0.060712,0.243544,720.919460,9.930793,0.000144,66.659875
4039,8.009618e+06,M,28.067674,18.477850,188.983008,2501.568981,0.114228,0.153200,0.324914,0.160105,0.638219,0.052020,0.212740,518.630280,9.119588,0.000130,66.388146
4170,1.721022e+07,M,28.162806,18.423548,187.660155,2495.909622,0.113917,0.153775,0.321273,0.160117,0.635165,0.051441,0.211722,518.858798,9.047941,0.000129,65.990493
4957,1.340805e+07,M,28.223878,18.528421,188.826181,2494.185419,0.114415,0.150205,0.321311,0.157775,0.629291,0.050695,0.209764,522.943912,9.068653,0.000129,66.239684

5.query METHOD

In [32]:
df.query('radius_mean >= 28')

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,shape_irregularity,border_complexity,tumor_aggressiveness,radius_texture_interaction,radius_concavity_interaction,concavity_density,malignancy_risk_score
373,9.557969e+06,M,28.226659,18.475831,188.331034,2496.606181,0.114306,0.151275,0.322009,0.158492,0.631776,0.051036,0.210592,521.510983,9.089236,0.000129,66.151952
497,3.680075e+06,M,28.134575,18.675329,188.730042,2507.933865,0.113976,0.151470,0.319505,0.160258,0.631233,0.051203,0.210411,525.422450,8.989126,0.000127,66.210220
575,1.485636e+07,M,28.037554,18.505108,187.798686,2507.982355,0.115066,0.151185,0.319866,0.157963,0.629014,0.050527,0.209671,518.837982,8.968264,0.000128,65.904800
1267,1.298915e+06,M,28.180977,18.450093,188.271693,2499.413980,0.114077,0.153222,0.323629,0.159020,0.635870,0.051463,0.211957,519.941649,9.120178,0.000129,66.179382
2653,9.562581e+06,M,28.085196,18.434952,188.552674,2507.574607,0.114925,0.153464,0.321570,0.160146,0.635180,0.051498,0.211727,517.749251,9.031344,0.000128,66.202363
3024,1.024661e+07,M,28.341004,18.354148,187.179338,2495.754833,0.114256,0.149376,0.317255,0.158960,0.625592,0.050431,0.208531,520.174975,8.991326,0.000127,65.785470
4039,8.009618e+06,M,28.067674,18.477850,188.983008,2501.568981,0.114228,0.153200,0.324914,0.160105,0.638219,0.052020,0.212740,518.630280,9.119588,0.000130,66.388146
4170,1.721022e+07,M,28.162806,18.423548,187.660155,2495.909622,0.113917,0.153775,0.321273,0.160117,0.635165,0.051441,0.211722,518.858798,9.047941,0.000129,65.990493
4957,1.340805e+07,M,28.223878,18.528421,188.826181,2494.185419,0.114415,0.150205,0.321311,0.157775,0.629291,0.050695,0.209764,522.943912,9.068653,0.000129,66.239684

6.filter METHOD

In [39]:
df.filter(regex='mean')

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean
0,11.829858,21.726166,75.154378,435.022394,0.087089,0.050717,0.015868,0.011641
1,10.991150,17.103260,71.798929,381.386295,0.089339,0.109498,0.097344,0.035629
2,21.433519,15.092437,142.753006,1392.399890,0.099557,0.152079,0.193372,0.126922
3,11.700452,14.872127,74.154481,404.112556,0.101291,0.077563,0.043749,0.028747
4,13.259377,17.212990,83.621014,521.124238,0.072905,0.043312,0.046983,0.010096
...,...,...,...,...,...,...,...,...
5495,11.688492,18.217548,75.277156,429.895271,0.113777,0.104274,0.069515,0.034620
5496,13.831066,19.454900,88.204429,580.072530,0.087240,0.061584,0.012322,0.022518
5497,19.403923,18.152520,127.631265,1129.627896,0.104142,0.144262,0.164108,0.094511
5498,20.946319,25.233666,142.498720,1340.103257,0.109454,0.226277,0.316075,0.148336
5499,19.936731,22.043719,129.216656,1269.726727,0.098140,0.102896,0.146180,0.096857

In [40]:
df.filter(items=['id','malignancy_risk_score'])

                id  malignancy_risk_score
0     5.683796e+06              22.433798
1    -6.253379e+06              24.021839
2     4.213892e+06              49.053992
3    -2.986069e+06              23.276145
4     6.469594e+05              25.647074
...            ...                    ...
5495  2.909607e+06              24.344788
5496  4.399236e+05              26.379882
5497 -4.461865e+06              43.224263
5498  7.519916e+06              52.471548
5499 -3.163711e+06              43.364274

[5500 rows x 2 columns]