<a href="https://colab.research.google.com/github/belindacarolam04/pandas_learning/blob/main/MERGE.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**MERGING**

In [19]:
import pandas as pd

In [20]:
employees=pd.DataFrame({'EmpId':[1,2,3,4],
                        'Name':['Alice','Bob','Charlie','David']})
print(employees)

   EmpId     Name
0      1    Alice
1      2      Bob
2      3  Charlie
3      4    David

In [21]:
salaries=pd.DataFrame({'EmpId':[1,2,3,5],
                       'Salary':[50000,60000,70000,80000]})
print(salaries)

   EmpId  Salary
0      1   50000
1      2   60000
2      3   70000
3      5   80000

TYPES OF MERGING

INNER JOIN-default

matching rows alone

In [22]:
(employees.merge(salaries,on='EmpId',how='inner'))

   EmpId     Name  Salary
0      1    Alice   50000
1      2      Bob   60000
2      3  Charlie   70000

LEFT JOIN

all rows from left and common between both

In [23]:
(employees.merge(salaries,on='EmpId',how='left'))

   EmpId     Name   Salary
0      1    Alice  50000.0
1      2      Bob  60000.0
2      3  Charlie  70000.0
3      4    David      NaN

RIGHT JOIN

rows from right and common in both

In [24]:
employees.merge(salaries,on='EmpId',how='right')

   EmpId     Name  Salary
0      1    Alice   50000
1      2      Bob   60000
2      3  Charlie   70000
3      5      NaN   80000

OUTER JOIN

combines all rows from both dataframe

In [25]:
employees.merge(salaries,on='EmpId',how='outer')

   EmpId     Name   Salary
0      1    Alice  50000.0
1      2      Bob  60000.0
2      3  Charlie  70000.0
3      4    David      NaN
4      5      NaN  80000.0

MERGING BASED ON DIFFERENT COLUMNS

In [26]:
df1 = pd.DataFrame({
    "ID":[1,2,3]
})

df2 = pd.DataFrame({
    "EmpId":[1,2,3],
    "Salary":[50000,60000,70000]
})

In [27]:
df1.merge(df2,left_on='ID',right_on='EmpId')

   ID  EmpId  Salary
0   1      1   50000
1   2      2   60000
2   3      3   70000

MERGE MULTIPLE COLUMNS

In [28]:
df3=pd.DataFrame({'Department':['HR','IT','Sales'],
                  'Name':['Alice','Bob','Monisha'],
                  'City':['New York','San Francisco','Los Angeles']})
print(df3)
df4=pd.DataFrame({'Department':['HR','IT','Sales'],
                  'Salary':[50000,60000,70000],'City':['New York','San Franciso','Los Angeles']})
print(df4)

  Department     Name           City
0         HR    Alice       New York
1         IT      Bob  San Francisco
2      Sales  Monisha    Los Angeles
  Department  Salary          City
0         HR   50000      New York
1         IT   60000  San Franciso
2      Sales   70000   Los Angeles

In [29]:
df3.merge(df4,on=['Department','City'],how='outer')

  Department     Name           City   Salary
0         HR    Alice       New York  50000.0
1         IT      Bob  San Francisco      NaN
2         IT      NaN   San Franciso  60000.0
3      Sales  Monisha    Los Angeles  70000.0

SUFFIXES FOR DUPLICATE COLUMNS

In [30]:
df3.merge(df4,on='Department',how='outer',suffixes=('_old','_new'))

  Department     Name       City_old  Salary      City_new
0         HR    Alice       New York   50000      New York
1         IT      Bob  San Francisco   60000  San Franciso
2      Sales  Monisha    Los Angeles   70000   Los Angeles

MERGE BASED ON INDEX

In [31]:
df3.merge(
    df4,
    left_index=True,
    right_index=True
)

  Department_x     Name         City_x Department_y  Salary        City_y
0           HR    Alice       New York           HR   50000      New York
1           IT      Bob  San Francisco           IT   60000  San Franciso
2        Sales  Monisha    Los Angeles        Sales   70000   Los Angeles

MERGING THREE DATAFRAMES

In [44]:
df5=pd.DataFrame({'EmpId':[1,2,3,4],

                  'Salary':[50000,60000,70000,40000]})
print(df5)

   EmpId  Salary
0      1   50000
1      2   60000
2      3   70000
3      4   40000

In [45]:
df5.merge(employees,on="EmpId").merge(df2,on="EmpId")

   EmpId  Salary_x     Name  Salary_y
0      1     50000    Alice     50000
1      2     60000      Bob     60000
2      3     70000  Charlie     70000

CROSS JOIN

Every row combines with every rows

In [46]:
df1.merge(df2,how='cross')

   ID  EmpId  Salary
0   1      1   50000
1   1      2   60000
2   1      3   70000
3   2      1   50000
4   2      2   60000
5   2      3   70000
6   3      1   50000
7   3      2   60000
8   3      3   70000

SOURCES OF ROWS

In [47]:
employees.merge(salaries,on='EmpId',how='outer',indicator=True)

   EmpId     Name   Salary      _merge
0      1    Alice  50000.0        both
1      2      Bob  60000.0        both
2      3  Charlie  70000.0        both
3      4    David      NaN   left_only
4      5      NaN  80000.0  right_only

VALIDATING MERGE

In [51]:
employees.merge(salaries,on='EmpId',how='outer',validate='many_to_one')

   EmpId     Name   Salary
0      1    Alice  50000.0
1      2      Bob  60000.0
2      3  Charlie  70000.0
3      4    David      NaN
4      5      NaN  80000.0