<a href="https://colab.research.google.com/github/belindacarolam04/pandas_learning/blob/main/Value_Counts.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**VALUE COUNTS**

In [2]:
import pandas as pd

In [3]:
import kagglehub

path = kagglehub.dataset_download(
    "shivasingh4945/enhanced-breast-cancer-diagnostic-dataset"
)

print("Path to dataset files:", path)

Downloading to /root/.cache/kagglehub/datasets/shivasingh4945/enhanced-breast-cancer-diagnostic-dataset/1.archive...

100%|██████████| 812k/812k [00:00<00:00, 65.3MB/s]

Extracting files...
Path to dataset files: /root/.cache/kagglehub/datasets/shivasingh4945/enhanced-breast-cancer-diagnostic-dataset/versions/1

In [4]:
import os

print(os.listdir(path))

['breast_cancer_enhanced_dataset.csv']

In [5]:
df=pd.read_csv(f"{path}/breast_cancer_enhanced_dataset.csv")

1.BASIC IMPLEMENTATION

In [6]:
df['diagnosis'].value_counts()

diagnosis
B    3470
M    2030
Name: count, dtype: int64

2.IN ASCENDING ORDER

In [7]:
df['diagnosis'].value_counts(ascending=True)

diagnosis
M    2030
B    3470
Name: count, dtype: int64

3.RELATIVE FREQUENCY

In [11]:
df['diagnosis'].value_counts(normalize=True)*100

diagnosis
B    63.090909
M    36.909091
Name: proportion, dtype: float64

4.DROP THE NULL ROWS

In [13]:
df['diagnosis'].value_counts(dropna=True)

diagnosis
B    3470
M    2030
Name: count, dtype: int64

5.USING APPLY AND VALUE COUNTS TOGETHER

In [18]:
df['area_mean'].apply(lambda x: "Dangerous" if x > 200 else "non dangerous").value_counts()

area_mean
Dangerous        5453
non dangerous      47
Name: count, dtype: int64